main: com.wolfhybrid23.spigot.shopgui.ShopGuiPlugin
description: A configurable item shop gui
version: 1.1
api-version: 1.16
name: ShopGui
authors: ["Woof Hybrid"]
depend: [Vault]
commands:
  shop:
    description: Opens the item shop.
permissions:
  shopgui.open.*:
    description: Allows you to open a GUI
    default: op
  shopgui.command.use:
    description: Allows you to use the command
    default: op
  shopgui.command.reload:
    description: Allows you to reload the plugin
    default: op
